### ISSUE TITLE
the detailed information about Attention LSTM

### ISSUE THREAD

**Issue by kevinhan2018** [titu1994/MLSTM-FCN#10]
Thank you for your excellent work. It actually inspires me a lot. Here is one question:
Could you give a detailed word description about the implemention of Attention LSTM layer in the layer
_utils.py ? In my opinion,  the paper Neural Machine Translation by Jointly Learning to Align and Translate introduce the attention mechanism in the encoder-decoder networks. However, you give a function that indicates a layer with LSTM.

**Comment by titu1994** [comment]
In the simplest explanation, this implementation can be considered as self-attention on input variables rather than on timesteps due to dimension shuffling. 

The original NMT uses the encoder outputs as what it focusses the attention on with a dot product with the current attention vector inside the decoder, whereas in the implementation here, the input itself acts as the "encoder output" over which attention is applied. 

With the understanding that this is self-attention over input rather than attention over the encoder embeddings, there is a 1:1 mapping to the paper.

**Comment by kevinhan2018** [comment]
Thank you for your reply. Could the outputs of AttentionLSTM be regarded as a new time-series? In other words, if I set the number of units in AttentionLSTM layer to be 100, the outputs of this layer is a vector whose shape is (100, ), what is the underlying meaning of this vector? Besides, the hidden states of LSTM is tuned according to the attention mechanism, so the input gate, output gate and forget gate should also be adjusted? Thank you!

**Comment by titu1994** [comment]
The output of both LSTM and Attention LSTM is generally a new multivariate time series of the hidden states of the model, with the same number of time steps but with number of variables set as number of cells. However we require only the last cell state for classification so it reduces to just a vector lf length "cell size" for every sample in the batch. 

The lstm and attention lsrm have two state vectors, ct and ht. Ht is the time series of cell states returned by the LSTM or the Attention LSTM, but we utilize only the last cell state. 

All the gates of the models are adjusted according to gradient descent.

**Comment by kevinhan2018** [comment]
Thank you for your guidance and help！
